service: testnet-v3-faucet

frameworkVersion: '3'
variablesResolutionMode: 20210326
useDotenv: true

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  profile: pelagos-dev
  region: us-east-2
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: ${opt:stage}-testnet-v3-faucet
      # https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html
      statements:
        -
          Effect: Allow
          Action:
            - 'ssm:DescribeParameters'
          Resource: '*'
        -
          Effect: Allow
          Action:
            - 'ssm:GetParameter'
          Resource: 'arn:aws:ssm:us-east-2:684317180556:parameter/${opt:stage}_testnet_v3_faucet_*'
        -
          Effect: Allow
          Action:
            - 'sqs:SendMessage'
            - 'sqs:DeleteMessage'
            - 'sqs:GetQueueAttributes'
            - 'sqs:ReceiveMessage'
          Resource: 'arn:aws:sqs:us-east-2:684317180556:${opt:stage}-testnet-v3-faucet.fifo'

functions:
  faucet:
    timeout: 29
    environment:
      AWS_SQS_URL: https://sqs.us-east-2.amazonaws.com/684317180556/${opt:stage}-testnet-v3-faucet.fifo
      DISCORD_APPLICATION_ID: ${ssm:/${opt:stage}_testnet_v3_faucet_discord_application_id}
      DISCORD_GUILD_ID: ${ssm:/${opt:stage}_testnet_v3_faucet_discord_discord_guild_id}
      DISCORD_CHANNEL_ID: ${ssm:/${opt:stage}_testnet_v3_faucet_discord_discord_channel_id}
      FAUCET_MNEMONIC: ${ssm:/${opt:stage}_testnet_v3_faucet_mnemonic}
      FAUCET_DATABASE_URI: ${ssm:/${opt:stage}_testnet_v3_faucet_database_uri}
    handler: faucet.open
    events:
      - sqs: 'arn:aws:sqs:us-east-2:684317180556:${opt:stage}-testnet-v3-faucet.fifo'
  listener:
    environment:
      AWS_SQS_URL: https://sqs.us-east-2.amazonaws.com/684317180556/${opt:stage}-testnet-v3-faucet.fifo
      DISCORD_APPLICATION_PUBLIC_KEY: ${ssm:/${opt:stage}_testnet_v3_faucet_discord_application_public_key}
      DISCORD_GUILD_ID: ${ssm:/${opt:stage}_testnet_v3_faucet_discord_discord_guild_id}
      DISCORD_CHANNEL_ID: ${ssm:/${opt:stage}_testnet_v3_faucet_discord_discord_channel_id}
      FAUCET_DATABASE_URI: ${ssm:/${opt:stage}_testnet_v3_faucet_database_uri}
    handler: listener.interactions
    events:
      -
        http:
          path: discord/interactions
          method: post
          cors: true
  observer:
    environment:
      FAUCET_DATABASE_URI: ${ssm:/${opt:stage}_testnet_v3_faucet_database_uri}
    handler: observer.overview
    events:
      -
        http:
          path: observer/overview
          method: get
          cors: true
  address:
    environment:
      FAUCET_DATABASE_URI: ${ssm:/${opt:stage}_testnet_v3_faucet_database_uri}
    handler: observer.address
    events:
      -
        http:
          path: observer/address/{address}
          method: get
          cors: true
          request:
            parameters:
               paths:
                 address: true
  health:
    timeout: 29
    handler: observer.health
    events:
      -
        http:
          path: observer/health
          method: get
          cors: true
